Provided alternate solution for power by using a recursive approach #25
DSC-IIITL/GitGrind pull request #48
Opened 2023-10-19 12:05 UTC by beforeIkillYou

Provides an alternate approach to the power function by converting its implementation to recursive #25

2023-10-19 12:28 UTC, beforeIkillYou commented
Hey @shishiro26 @akhilender-bongirwar @Illuminati9 @Kota-Karthik the approach i went for solving this issue is pretty straightforward.
Instead of finding the power iteratively i went for a recursive approach which uses basic recursion for raising the base to a specified power.


![Screenshot 2023-10-19 175204](https://github.com/DSC-IIITL/GitGrind/assets/70949548/a93762fe-23ad-428b-8f75-d8abd0c83c99)

This above written function by me is the direct implementation of recursive exponentiation algorithm and this image gives a pretty clear view of how it works-

![Screenshot 2023-10-19 175629](https://github.com/DSC-IIITL/GitGrind/assets/70949548/831e5015-bbce-4ced-9068-26d3f80b6d51)

2023-10-20 08:29 UTC, akhilender-bongirwar requested changes
@beforeIkillYou, remove all the commented code.

2023-10-20 10:13 UTC, beforeIkillYou commented
Hey @akhilender-bongirwar @Illuminati9 @PavanaSakethaRam , removed all the commented code from issue #25 and provided a solution using a recursive approach.

2023-10-21 12:16 UTC, akhilender-bongirwar approved these changes

2023-10-21 12:16 UTC, akhilender-bongirwar commented on Students/LCI2023038/power.cpp
> +// (Do you want a hint?).
@beforeIkillYou , remove these commented lines also.

2023-10-21 12:17 UTC, shishiro26 requested changes
Please do follow the folder structure for the solutions. Make sure to create a folder for the type of problem you are approaching or solving. @beforeIkillYou . solve it asap

2023-10-21 12:20 UTC, akhilender-bongirwar requested changes
Follow folder structure you need to create a new folder "Alternate_Solution" inside LCI2023038 and then add power.cpp

2023-10-21 16:04 UTC, beforeIkillYou commented
Hello @akhilender-bongirwar @Illuminati9 @shishiro26 @Kota-Karthik , i completed all the required changes . Made the required folders and commented all the unnecessary code and and text.

2023-10-21 16:09 UTC, shishiro26 reviewed
@beforeIkillYou, you have created another 'power.cpp' file in the 'lci2023038' folder. Please remove the one in the 'lci2023038' folder.

2023-10-21 16:45 UTC, beforeIkillYou commented
Hello @akhilender-bongirwar @Illuminati9 @shishiro26 @Kota-Karthik , i completed all the required changes . Removed the 'power.cpp' file.

2023-10-21 17:00 UTC, shishiro26 approved these changes
LGTM 👏

2023-10-21 17:00 UTC, shishiro26 commented on Students/LCI2023038/power.cpp
Remove this file

2023-10-21 17:29 UTC, akhilender-bongirwar approved these changes

2023-10-21 17:49 UTC, Illuminati9 approved these changes
LGTM

2023-10-21 17:53 UTC, PavanaSakethaRam approved these changes

2023-10-21 17:53 UTC, merged