Fix Bugs in Sorting Problem, issue #21
DSC-IIITL/GitGrind pull request #51
Opened 2023-10-20 10:18 UTC by gauravghodinde

removed unnecessary variables and while loop in main function.

Screenshot of output
![image](https://github.com/DSC-IIITL/GitGrind/assets/65962770/2d8adef0-960f-484b-92b7-bcf893d2f7c4)

2023-10-21 09:13 UTC, Kota-Karthik approved these changes

2023-10-21 12:09 UTC, akhilender-bongirwar requested changes
@gauravghodinde, remove the .exe file. solve it asap

2023-10-21 15:21 UTC, gauravghodinde commented
@akhilender-bongirwar which .exe file are you referring to I removed all the exe files in the last commit.

2023-10-21 17:34 UTC, akhilender-bongirwar approved these changes

2023-10-22 07:25 UTC, shishiro26 approved these changes

2023-10-22 10:32 UTC, Illuminati9 approved these changes
LGTM

2023-10-22 11:28 UTC, merged