Added a more optimized solution using Insertion Sort Algorithm for sorting.cpp issue #35
DSC-IIITL/GitGrind pull request #52
Opened 2023-10-20 10:57 UTC by digvijay2406

Here I have used the Insertion Sort Algorithm to find a more optimized solution of issue #35 sorting.cpp

It is a simple sorting algorithm that builds the final sorted array one element at a time, efficiently placing each element in its correct position within the sorted portion. It has a time complexity of O(n^2) and is suitable for small datasets.

2023-10-21 09:12 UTC, Kota-Karthik approved these changes

2023-10-21 12:09 UTC, shishiro26 requested changes
Remove the .exe file @digvijay2406.solve it asap

2023-10-21 16:38 UTC, shishiro26 approved these changes
LGTM 👏

2023-10-22 10:30 UTC, Illuminati9 approved these changes
LGTM

2023-10-22 11:29 UTC, akhilender-bongirwar approved these changes

2023-10-22 11:29 UTC, merged